#
# Configuration MamiyaFumin
# Version: 0.6
# Author: rnlin
#

enablefumin: true
ScoreboardDisplayHours: 10
FuminPointMagnification: 40
SpawnPhantomMessage: "§8あなたはファントムが出現するほど起き続けています。"
PlayerDeathMessage: null