name: MamiyaFumin
main: com.github.rnlin.MamiyaFumin
version: 0.1.0
author: rnlin
description: MamiyaFumin

commands:
  MamiyaFumin:
    description: It's main commands of this plugin.
    aliases: [mf,mfm]
    usage: 
           /<command>
    permisson: mamiya.fumin.main
    permisson: mamiya.fumin.command.mamiyafumin
    permission-message: You don't have the permission "<permission>".
  fumintop:
    description: It's fumintop
  fuminstats:
    description: It's fuminstats
    aliases: [fs]
  fuminrank:
    description: it's fuminrank
      
permissions:
  mamiya.fumin.command.mamiyafumin:
    description: mamiyafuminコマンドの使用権限
    default: op